spring:
  application:
    name: lonjas
    id: com.sphirye.lonjas

  config:
    import: optional:file:.env[.properties]

  profiles:
    active:

  datasource:
    url: jdbc:mysql://lonjasdb:3306/lonjasdb
    username: root
    password: 1234

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    enabled: true

server:
  port: 3000
  error:
    include-message: always

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 1250

custom:
  twitter-token: ${TWITTER_BEARER_TOKEN}